accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'
urlpatterns = [
    path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
]

articles/urls.py
from django.urls import path,re_path
from  . import views
app_name = 'articles'
urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/',views.article_create,name="create"),
    path('<slug:slug>/', views.article_detail, name='detail'),
]

djangonautic/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from  django.conf import settings
from  articles import views as article_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', article_view.article_list,name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title =models.CharField(max_length=100)
    body =models.TextField()
    slug =models.SlugField()
    date =models.DateTimeField(auto_now_add=True)
    thumb =models.ImageField(upload_to='images/',default='default.jpg',blank=True)
    audio = models.FileField(upload_to='audio/', blank=True)
    video = models.FileField(upload_to='video/', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
  
    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50]+'...'
    
    
    

articles/forms.py
from django import forms
from . import models
class  createArticel(forms.ModelForm):
    class Meta:
        model=models.Article
        fields=['title','body','slug','thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})
def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user =form.get_user()
            login(request,user)
            if 'next'in request.POST:
                return redirect(request.POST.get('next'))
            else:
            
                return redirect('articles:list')
    else:
        form=AuthenticationForm()
    return render(request,'accounts/login.html',{"form":form})
def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('articles:list')
        

articles/views.py
from django.shortcuts import render,get_object_or_404,redirect

from .models import Article
from django.http import HttpResponse
from  django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def article_list(request,):
    articles =Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})
def article_detail(request, slug):
    
    
    article = get_object_or_404(Article, slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})
    # return HttpResponse(slug)
@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method=='POST':
        form=forms.createArticel(request.POST,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('articles:list')
    else:
        form=forms.createArticel()
        
   
    return render(request,'articles/article_create.html',{'form':form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render
def about(request):
    # return HttpResponse('this is about page after i  correct the rgulare expression ')
    return render(request,'about.html')
def homePage(request):
    # return HttpResponse("this is home page")
    return  render(request,'homePage.html')
    

accounts/templates/accounts/login.html
{% extends "base_layout.html" %}
{% block content %}
<h1>login page </h1>

<form class="site_form" action='{% url 'accounts:login' %}' method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}

    <input type="hidden"value='{{request.GET.next}}'name='next'>
    {% endif %}
    <input type="submit"value='Login'>
</form>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base_layout.html" %}
{% block content %}

<form class="site_form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit"value='Signup'>
</form>

{% endblock content %}

articles/templates/articles/article_create.html
{% extends "base_layout.html" %}
{% block content %}
<div class="create_article">
    <h1>Create An Awesome Article </h1>
    <form class="site_form"action="{% url 'articles:create' %}"method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit"value="Create">
    </form>
    <h2>this is the end block</h2>

</div>

{% endblock content %}

articles/templates/articles/article_detail.html
{% extends "base_layout.html" %}
{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" alt="Thumbnail"width="auto"height="auto">
        <h2>{{ article.title }}</h2>
        <h3>Written by {{ article.author.username }}</h3>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
        
        {% if article.audio %}
            <audio controls>
                <source src="{{ article.audio.url }}" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        {% endif %}
        <br>
        <br>

        {% if article.video %}
            <video controls>
                <source src="{{ article.video.url }}" type="video/mp4">
                Your browser does not support the video element.
            </video>
        {% endif %}
    </div>
</div>
{% endblock content %}

articles/templates/articles/article_list.html
{% extends "base_layout.html" %}

{% block content %}
    <h1>This is the the  Articles List</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                <p>{{ article.snippet }}</p>
                <p>{{ article.date }}</p>
                <p class="author">added by {{ article.author.username }}</p>
                
            </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About  us</title>
</head>
<body>
    <h1>this is about page</h1>
    
</body>
</html>

templates/base_layout.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Djangonauts</title>
    <meta name="description" content="Your webpage description here">
    <meta name="keywords" content="keyword1, keyword2, keyword3">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <header class="wrapper">
        <h1>
            <a class="logo" href="{% url 'home' %}"><img src="{%static 'images/logo.png' %}" alt="djangonautic" height="100px" width="100px" /></a>
        </h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %} {% endblock %}
    </div>
</body>

</html>

templates/homePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home page</title>
</head>
<body>
    <h1>this is home page</h1>
    <p>well come to django tutorial</p>
</body>
</html>